#############################################################################
# Makefile for building: uart_my
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  ../uart_my/uart_my.pro
# Template: app
# Command: /home/inthedark/program/Qt5.3.1/5.3/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile ../uart_my/uart_my.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_SERIALPORT_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../program/Qt5.3.1/5.3/gcc_64/mkspecs/linux-g++ -I../uart_my -I../../program/Qt5.3.1/5.3/gcc_64/include -I../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets -I../../program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort -I../../program/Qt5.3.1/5.3/gcc_64/include/QtGui -I../../program/Qt5.3.1/5.3/gcc_64/include/QtCore -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/inthedark/program/Qt5.3.1/5.3/gcc_64 -Wl,-rpath,/home/inthedark/program/Qt5.3.1/5.3/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/inthedark/program/Qt5.3.1/5.3/gcc_64/lib -lQt5Widgets -lQt5SerialPort -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/inthedark/program/Qt5.3.1/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../uart_my/main.cpp \
		../uart_my/mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = ../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/unix.conf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/linux.conf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/qconfig.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/default_post.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/resources.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/moc.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/uic.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/yacc.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/lex.prf \
		../uart_my/uart_my.pro ../uart_my/main.cpp \
		../uart_my/mainwindow.cpp
QMAKE_TARGET  = uart_my
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = uart_my


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../uart_my/uart_my.pro ../../program/Qt5.3.1/5.3/gcc_64/mkspecs/linux-g++/qmake.conf ../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/unix.conf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/linux.conf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/qconfig.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/default_post.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/resources.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/moc.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/uic.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/yacc.prf \
		../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/lex.prf \
		../uart_my/uart_my.pro \
		/home/inthedark/program/Qt5.3.1/5.3/gcc_64/lib/libQt5Widgets.prl \
		/home/inthedark/program/Qt5.3.1/5.3/gcc_64/lib/libQt5Gui.prl \
		/home/inthedark/program/Qt5.3.1/5.3/gcc_64/lib/libQt5Core.prl \
		/home/inthedark/program/Qt5.3.1/5.3/gcc_64/lib/libQt5SerialPort.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile ../uart_my/uart_my.pro
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/spec_pre.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/shell-unix.conf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/unix.conf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/linux.conf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/gcc-base.conf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/g++-base.conf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/common/g++-unix.conf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/qconfig.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt_functions.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt_config.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/spec_post.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/default_pre.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/resolve_config.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/default_post.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/warn_on.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/qt.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/resources.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/moc.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/unix/opengl.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/uic.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/unix/thread.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/exceptions.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/yacc.prf:
../../program/Qt5.3.1/5.3/gcc_64/mkspecs/features/lex.prf:
../uart_my/uart_my.pro:
/home/inthedark/program/Qt5.3.1/5.3/gcc_64/lib/libQt5Widgets.prl:
/home/inthedark/program/Qt5.3.1/5.3/gcc_64/lib/libQt5Gui.prl:
/home/inthedark/program/Qt5.3.1/5.3/gcc_64/lib/libQt5Core.prl:
/home/inthedark/program/Qt5.3.1/5.3/gcc_64/lib/libQt5SerialPort.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile ../uart_my/uart_my.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/uart_my1.0.0 || mkdir -p .tmp/uart_my1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/uart_my1.0.0/ && $(COPY_FILE) --parents ../uart_my/mainwindow.h .tmp/uart_my1.0.0/ && $(COPY_FILE) --parents ../uart_my/main.cpp ../uart_my/mainwindow.cpp .tmp/uart_my1.0.0/ && $(COPY_FILE) --parents ../uart_my/mainwindow.ui .tmp/uart_my1.0.0/ && (cd `dirname .tmp/uart_my1.0.0` && $(TAR) uart_my1.0.0.tar uart_my1.0.0 && $(COMPRESS) uart_my1.0.0.tar) && $(MOVE) `dirname .tmp/uart_my1.0.0`/uart_my1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/uart_my1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/QMainWindow \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qwidget.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qobject.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qlist.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qiterator.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qmetatype.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qisenum.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qmargins.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qrect.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qsize.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qpoint.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qpalette.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qcolor.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qrgb.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringlist.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qdatastream.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qiodevice.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qpair.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qregexp.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qbrush.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qvector.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qmatrix.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qpolygon.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qregion.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qline.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qtransform.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qimage.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qpixmap.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qshareddata.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qhash.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qfont.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qfontinfo.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qcursor.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qevent.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qvariant.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qmap.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qdebug.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qtextstream.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qlocale.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qset.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qurl.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qurlquery.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qfile.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qvector2d.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qicon.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort/QSerialPort \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort/qserialport.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort/qserialportglobal.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort/QSerialPortInfo \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort/qserialportinfo.h \
		../uart_my/mainwindow.h
	/home/inthedark/program/Qt5.3.1/5.3/gcc_64/bin/moc $(DEFINES) -I/home/inthedark/program/Qt5.3.1/5.3/gcc_64/mkspecs/linux-g++ -I/home/inthedark/qt/uart_my -I/home/inthedark/program/Qt5.3.1/5.3/gcc_64/include -I/home/inthedark/program/Qt5.3.1/5.3/gcc_64/include/QtWidgets -I/home/inthedark/program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort -I/home/inthedark/program/Qt5.3.1/5.3/gcc_64/include/QtGui -I/home/inthedark/program/Qt5.3.1/5.3/gcc_64/include/QtCore -I. ../uart_my/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ../uart_my/mainwindow.ui
	/home/inthedark/program/Qt5.3.1/5.3/gcc_64/bin/uic ../uart_my/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../uart_my/main.cpp ../uart_my/mainwindow.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/QMainWindow \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qwidget.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qobject.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qlist.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qiterator.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qmetatype.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qisenum.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qmargins.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qrect.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qsize.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qpoint.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qpalette.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qcolor.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qrgb.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringlist.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qdatastream.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qiodevice.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qpair.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qregexp.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qbrush.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qvector.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qmatrix.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qpolygon.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qregion.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qline.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qtransform.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qimage.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qpixmap.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qshareddata.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qhash.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qfont.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qfontinfo.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qcursor.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qevent.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qvariant.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qmap.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qdebug.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qtextstream.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qlocale.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qset.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qurl.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qurlquery.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qfile.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qvector2d.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qicon.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort/QSerialPort \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort/qserialport.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort/qserialportglobal.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort/QSerialPortInfo \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort/qserialportinfo.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/QApplication \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qapplication.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qeventloop.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qguiapplication.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../uart_my/main.cpp

mainwindow.o: ../uart_my/mainwindow.cpp ../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/QDebug \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qdebug.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qhash.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qiterator.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qlist.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qpair.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qmap.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qtextstream.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qiodevice.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qobject.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qmetatype.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qisenum.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qlocale.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qvariant.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringlist.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qdatastream.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qregexp.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qshareddata.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qvector.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qpoint.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qset.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../uart_my/mainwindow.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/QMainWindow \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qwidget.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qmargins.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qrect.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qsize.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qpalette.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qcolor.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qrgb.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qbrush.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qmatrix.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qpolygon.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qregion.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qline.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qtransform.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qimage.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qpixmap.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qfont.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qfontinfo.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qcursor.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qevent.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qurl.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qurlquery.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qfile.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qvector2d.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qicon.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort/QSerialPort \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort/qserialport.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort/qserialportglobal.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort/QSerialPortInfo \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtSerialPort/qserialportinfo.h \
		ui_mainwindow.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/QListWidget \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qlistwidget.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qlistview.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qframe.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qstyleoption.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtGui/qvalidator.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtCore/qregularexpression.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qslider.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qabstractslider.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qstyle.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qtabbar.h \
		../../program/Qt5.3.1/5.3/gcc_64/include/QtWidgets/qrubberband.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../uart_my/mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

